version: '3'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: leader
    volumes:
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    ports:
      - "3306:3306"
